# Generated by Django 4.2.16 on 2026-05-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_notified',
            field=models.DateTimeField(blank=True, help_text='When the most recent notification email was dispatched.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_every',
            field=models.PositiveSmallIntegerField(default=4, help_text='Hours between automated notification emails.'),
        ),
    ]
