"""Ordered catalogue of the concrete sensor reading models.

``SENSOR_MODELS`` drives the auto-generated per-sensor read/PATCH routes in
``apps.sensors.router_sensors``. Relocated from ``analytics/sensor_registry.py``
(Phase 5b); the legacy DRF serializer/view generation loop that used to live
here was dead (superseded by the django-ninja sensors router) and was dropped.
"""

from .models import (
    EcSalinitySensor,
    ECSoilHigh,
    ECSoilLow,
    ECSoilMedium,
    ElectricityConsumptionSensor,
    Et0Calculated,
    Et0Weather,
    FruitSizeSensor,
    HumidityWeather,
    LargeFruitDiameterSensor,
    LeafMoistureSensor,
    LeafTemperatureSensor,
    MultiDepthSoilMoistureSensor,
    NpkSensor,
    BatterySensor,
    PhSoil,
    PhWaterSensor,
    PrecipitationRate,
    SignalSensor,
    PressureWeather,
    SoilConductivitySensor,
    SoilMoistureHigh,
    SoilMoistureLow,
    SoilMoistureMedium,
    SoilSalinitySensor,
    SoilTemperatureHigh,
    SoilTemperatureLow,
    SoilTemperatureMedium,
    SolarRadiation,
    TemperatureWeather,
    VPDWeather,
    WaterECSensor,
    WaterFlowSensor,
    WaterLevelSensor,
    WaterPressureSensor,
    WindDirection,
    WindSpeed,
)

SENSOR_MODELS = [
    PrecipitationRate,
    HumidityWeather,
    WindSpeed,
    SolarRadiation,
    PressureWeather,
    WindDirection,
    TemperatureWeather,
    ECSoilMedium,
    SoilTemperatureMedium,
    ECSoilHigh,
    ECSoilLow,
    SoilMoistureMedium,
    SoilMoistureHigh,
    SoilMoistureLow,
    PhSoil,
    SoilTemperatureLow,
    SoilTemperatureHigh,
    WaterFlowSensor,
    WaterECSensor,
    PhWaterSensor,
    ElectricityConsumptionSensor,
    LeafMoistureSensor,
    MultiDepthSoilMoistureSensor,
    LargeFruitDiameterSensor,
    WaterLevelSensor,
    SoilConductivitySensor,
    Et0Weather,
    Et0Calculated,
    # VPD is computed hourly by compute_et0_vpd_hourly (same task as ET0) and
    # stored in VPDWeather. Exposing it here gives the DPV chart a server-side
    # series (slug: vpdweather) instead of a fragile client-side join.
    VPDWeather,
    LeafTemperatureSensor,
    SoilSalinitySensor,
    NpkSensor,
    FruitSizeSensor,
    EcSalinitySensor,
    WaterPressureSensor,
    BatterySensor,
    SignalSensor,
]
