"""
Plug-and-play alert engine.

Anything that produces a numeric reading (a sensor model in this app) can
have an alert attached to it via a stable ``sensor_key``. Charts on the
frontend look up alerts for the same key + zone and render them as
threshold lines / event markers.

Layout:

    1. SENSOR_KEY_REGISTRY      — string key -> (model, default_unit)
    2. evaluate(condition, threshold, value) — pure threshold check
    3. evaluate_alert(alert, value)           — bound to an Alert row
    4. latest_value_for(alert)                — most recent reading (DB)
    5. recent_triggers_for_user(user)         — fan-out used by the API

The whole module is intentionally I/O-light so unit tests can call
``evaluate`` and ``evaluate_alert`` with mocked numbers and zero DB.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Iterable

from django.utils import timezone


# ----- 1. Sensor-key registry ----------------------------------------------

# These keys match the dataKey strings used by the frontend recharts panels
# and the sensor URL slugs auto-generated by ``sensor_registry``. Keep this
# list in sync; tests assert that every key resolves to a real model.
SENSOR_KEY_REGISTRY: dict[str, dict[str, Any]] = {
    "temperature_weather": {
        "model": "TemperatureWeather",
        "unit": "°C",
        "label": "Température de l'air",
        "type": "Weather Temperature",
    },
    "humidity_weather": {
        "model": "HumidityWeather",
        "unit": "%",
        "label": "Humidité de l'air",
        "type": "Humidity",
    },
    "wind_speed": {
        "model": "WindSpeed",
        "unit": "m/s",
        "label": "Vitesse du vent",
        "type": "Wind Speed",
    },
    "solar_radiation": {
        "model": "SolarRadiation",
        "unit": "W/m²",
        "label": "Rayonnement solaire",
        "type": "Weather Temperature",
    },
    "pressure_weather": {
        "model": "PressureWeather",
        "unit": "hPa",
        "label": "Pression atmosphérique",
        "type": "Pressure",
    },
    "precipitation_rate": {
        "model": "PrecipitationRate",
        "unit": "mm/h",
        "label": "Précipitations",
        "type": "Rain Fall",
    },
    "et0": {
        "model": "Et0Calculated",
        "unit": "mm/h",
        "label": "ET₀",
        "type": "Weather Temperature",
    },
    "soil_moisture_medium": {
        "model": "SoilMoistureMedium",
        "unit": "%",
        "label": "Humidité du sol",
        "type": "Humidity",
    },
    "soil_temperature_medium": {
        "model": "SoilTemperatureMedium",
        "unit": "°C",
        "label": "Température du sol",
        "type": "Soil Temperature",
    },
    "soil_ph": {
        "model": "PhSoil",
        "unit": "pH",
        "label": "pH du sol",
        "type": "pH Level",
    },
    "water_flow": {
        "model": "WaterFlowSensor",
        "unit": "m³/h",
        "label": "Débit d'eau",
        "type": "Flow",
    },
    "water_pressure": {
        "model": "WaterPressureSensor",
        "unit": "bar",
        "label": "Pression d'eau",
        "type": "Pressure",
    },
    "ph_water": {
        "model": "PhWaterSensor",
        "unit": "pH",
        "label": "pH de l'eau",
        "type": "pH Level",
    },
    "water_ec": {
        "model": "WaterECSensor",
        "unit": "μS/cm",
        "label": "Conductivité de l'eau",
        "type": "EC (Electrical Conductivity)",
    },
    "soil_conductivity": {
        "model": "SoilConductivitySensor",
        "unit": "μS/cm",
        "label": "Conductivité du sol",
        "type": "EC (Electrical Conductivity)",
    },
    "soil_salinity": {
        "model": "SoilSalinitySensor",
        "unit": "mg/L",
        "label": "Salinité du sol",
        "type": "EC (Electrical Conductivity)",
    },
    "leaf_moisture": {
        "model": "LeafMoistureSensor",
        "unit": "%",
        "label": "Humidité foliaire",
        "type": "Humidity",
    },
    "leaf_temperature": {
        "model": "LeafTemperatureSensor",
        "unit": "°C",
        "label": "Température foliaire",
        "type": "Soil Temperature",
    },
    "fruit_size": {
        "model": "FruitSizeSensor",
        "unit": "mm",
        "label": "Taille des fruits",
        "type": "Periodic maintenance",
    },
    "large_fruit_diameter": {
        "model": "LargeFruitDiameterSensor",
        "unit": "mm",
        "label": "Diamètre des gros fruits",
        "type": "Periodic maintenance",
    },
    "electricity_consumption": {
        "model": "ElectricityConsumptionSensor",
        "unit": "kWh",
        "label": "Consommation électrique",
        "type": "Periodic maintenance",
    },
}


def get_sensor_model(sensor_key: str):
    """Resolve a sensor_key to its Django model class. KeyError when unknown."""
    from analytics import models as analytics_models

    spec = SENSOR_KEY_REGISTRY[sensor_key]
    return getattr(analytics_models, spec["model"])


# ----- 2. Pure threshold check ---------------------------------------------

GREATER_THAN = ">"
LESS_THAN = "<"
EQUAL_TO = "="

# Tolerance used for the "=" condition so floating-point noise from sensors
# doesn't make the predicate impossible to satisfy in practice.
EQUALITY_TOLERANCE = 1e-3


def evaluate(condition: str, threshold: float, value: float | None) -> bool:
    """
    Pure threshold check. Returns False when ``value`` is None so missing
    readings never fire an alert.

    >>> evaluate(">", 30, 32)
    True
    >>> evaluate(">", 30, None)
    False
    """
    if value is None:
        return False
    if condition == GREATER_THAN:
        return value > threshold
    if condition == LESS_THAN:
        return value < threshold
    if condition == EQUAL_TO:
        return abs(value - threshold) <= EQUALITY_TOLERANCE
    raise ValueError(f"Unknown alert condition: {condition!r}")


# ----- 3. Bind to an Alert row ---------------------------------------------


def evaluate_alert(alert, value: float | None) -> bool:
    """True when ``value`` violates the alert's threshold."""
    return evaluate(alert.condition, float(alert.condition_nbr), value)


# ----- 4. Latest reading helper --------------------------------------------


@dataclass
class LatestReading:
    value: float | None
    timestamp: datetime | None


def latest_value_for(alert) -> LatestReading:
    """
    Most recent value the alert applies to. Falls back to the alert's owner
    when no zone is configured. ``LatestReading(None, None)`` if nothing is
    available so callers don't need to handle DoesNotExist.
    """
    if not alert.sensor_key or alert.sensor_key not in SENSOR_KEY_REGISTRY:
        return LatestReading(None, None)

    model = get_sensor_model(alert.sensor_key)
    qs = model.objects.all()
    if alert.zone_id:
        qs = qs.filter(zone_id=alert.zone_id)
    elif alert.user_id:
        qs = qs.filter(user_id=alert.user_id)
    row = qs.order_by("-timestamp").first()
    if row is None:
        return LatestReading(None, None)
    return LatestReading(value=row.value, timestamp=row.timestamp)


# ----- 5. Fan-out ----------------------------------------------------------


def recent_triggers_for_user(
    user, *, sensor_key: str | None = None, zone_id: int | None = None
) -> list[dict[str, Any]]:
    """
    Return every active alert for ``user`` (optionally filtered to one
    sensor/zone) annotated with its latest value, whether it's currently
    triggered, and the canonical threshold for chart overlays.
    """
    from analytics.models import Alert

    qs = Alert.objects.filter(user=user, is_active=True)
    if sensor_key:
        qs = qs.filter(sensor_key=sensor_key)
    if zone_id:
        qs = qs.filter(zone_id=zone_id)

    out: list[dict[str, Any]] = []
    now = timezone.now()
    for alert in qs.order_by("id"):
        latest = latest_value_for(alert)
        triggered = evaluate_alert(alert, latest.value)
        if triggered and not alert.last_triggered_at:
            alert.last_triggered_at = now
            alert.save(update_fields=["last_triggered_at"])
        out.append(
            {
                "id": alert.id,
                "name": alert.name,
                "sensor_key": alert.sensor_key,
                "zone_id": alert.zone_id,
                "condition": alert.condition,
                "threshold": float(alert.condition_nbr),
                "unit": SENSOR_KEY_REGISTRY.get(alert.sensor_key, {}).get("unit"),
                "label": SENSOR_KEY_REGISTRY.get(alert.sensor_key, {}).get("label"),
                "is_active": alert.is_active,
                "latest_value": latest.value,
                "latest_timestamp": latest.timestamp.isoformat()
                if latest.timestamp
                else None,
                "is_triggered": triggered,
                "last_triggered_at": (
                    alert.last_triggered_at.isoformat()
                    if alert.last_triggered_at
                    else None
                ),
            }
        )
    return out


def assert_keys_resolve(keys: Iterable[str]) -> None:
    """Test helper: every key in the registry must point at a live model."""
    for key in keys:
        get_sensor_model(key)


# ----- 6. Suggestion (mean-based prefill for the alert form) ----------------


def suggest_alert(
    user, *, sensor_key: str, zone_id: int | None = None, sample_size: int = 50
) -> dict[str, Any] | None:
    """
    Build a sensible default payload for the create-alert form: name based
    on the sensor's French label, threshold equal to the mean of the most
    recent ``sample_size`` readings (clipped to two decimals), condition
    that fires when the sensor strays from the mean, plus a description
    explaining where the threshold came from.

    Returns None when the sensor key is unknown.
    """
    if sensor_key not in SENSOR_KEY_REGISTRY:
        return None

    spec = SENSOR_KEY_REGISTRY[sensor_key]
    model = get_sensor_model(sensor_key)

    qs = model.objects.all()
    if user is not None:
        qs = qs.filter(user=user)
    if zone_id:
        qs = qs.filter(zone_id=zone_id)

    # Pull the latest N rows then average their .value (or, for NPK-style
    # rows that lack `value`, fall back gracefully to None).
    recent = list(
        qs.order_by("-timestamp").values_list("value", flat=True)[:sample_size]
    )
    valid = [float(v) for v in recent if v is not None]
    mean = round(sum(valid) / len(valid), 2) if valid else None

    # Default to "greater than mean" — the most common alert pattern. For
    # a soil-moisture sensor "below mean" is more useful, so we flip.
    condition = "<" if sensor_key.startswith("soil_moisture") else ">"

    threshold = mean if mean is not None else 0.0
    name = f"Alerte — {spec['label']}"
    description = (
        f"Seuil prérempli depuis la moyenne des {len(valid)} dernières lectures "
        f"({mean} {spec['unit']})."
        if valid
        else "Aucune lecture récente — ajustez le seuil manuellement."
    )

    return {
        "sensor_key": sensor_key,
        "label": spec["label"],
        "unit": spec["unit"],
        "type": spec.get("type", "Weather Temperature"),
        "name": name,
        "description": description,
        "condition": condition,
        "condition_nbr": threshold,
        "mean": mean,
        "sample_size": len(valid),
        "is_active": True,
    }
