# Generated by Django 4.2.16 on 2026-05-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0056_vpdweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor_key',
            field=models.CharField(blank=True, default='', help_text="Stable sensor identifier for chart overlays (e.g. 'temperature_weather').", max_length=64),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_alerts', to='analytics.zone'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition_nbr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the alert.'),
        ),
    ]
