# Generated by Django 4.2.16 on 2026-05-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0058_user_sensor_unit_preference_and_manager_affirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
