# Generated by Django 4.2.16 on 2026-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0060_signalsensor_batterysensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="notify_whatsapp",
            field=models.BooleanField(default=False),
        ),
    ]
