# Generated by Django 4.2.16 on 2026-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0061_alert_notify_email_alert_notify_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="elevation_m",
            field=models.FloatField(
                default=0,
                help_text="Elevation above sea level in metres (for clear-sky radiation Rso).",
            ),
        ),
    ]
