# Generated by Django 4.2.16 on 2026-06-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0064_alert_grace_override_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="activegraph",
            name="water_level_status",
            field=models.BooleanField(default=False, help_text="Niveau d'eau"),
        ),
    ]
