# Generated by Django 4.2.16 on 2026-06-26 01:00

from django.db import migrations, models


def activate_water_level(apps, schema_editor):
    ActiveGraph = apps.get_model("analytics", "ActiveGraph")
    ActiveGraph.objects.filter(water_level_status=False).update(water_level_status=True)


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0065_activegraph_water_level_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activegraph",
            name="water_level_status",
            field=models.BooleanField(default=True, help_text="Niveau d'eau"),
        ),
        migrations.RunPython(activate_water_level, migrations.RunPython.noop),
    ]
